
-- Create mcp_discovery_watchlist table
CREATE TABLE public.mcp_discovery_watchlist (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  company_name text NOT NULL,
  domain text NOT NULL,
  github_org text,
  docs_url text,
  last_checked_at timestamptz,
  status text NOT NULL DEFAULT 'watching',
  discovered_mcp_url text,
  discovered_repo_url text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(domain)
);

-- Enable RLS
ALTER TABLE public.mcp_discovery_watchlist ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can manage watchlist" ON public.mcp_discovery_watchlist
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Service role watchlist" ON public.mcp_discovery_watchlist
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Seed ~80 high-value companies
INSERT INTO public.mcp_discovery_watchlist (company_name, domain, github_org, docs_url) VALUES
  ('Adobe', 'adobe.com', 'adobe', 'https://developer.adobe.com'),
  ('Figma', 'figma.com', 'figma', 'https://www.figma.com/developers'),
  ('Canva', 'canva.com', 'canva', 'https://www.canva.dev'),
  ('Stripe', 'stripe.com', 'stripe', 'https://docs.stripe.com'),
  ('Vercel', 'vercel.com', 'vercel', 'https://vercel.com/docs'),
  ('Netlify', 'netlify.com', 'netlify', 'https://docs.netlify.com'),
  ('Datadog', 'datadoghq.com', 'DataDog', 'https://docs.datadoghq.com'),
  ('Sentry', 'sentry.io', 'getsentry', 'https://docs.sentry.io'),
  ('Linear', 'linear.app', 'linear', 'https://linear.app/docs'),
  ('Notion', 'notion.so', 'makenotion', 'https://developers.notion.com'),
  ('Shopify', 'shopify.com', 'Shopify', 'https://shopify.dev'),
  ('HubSpot', 'hubspot.com', 'HubSpot', 'https://developers.hubspot.com'),
  ('Twilio', 'twilio.com', 'twilio', 'https://www.twilio.com/docs'),
  ('SendGrid', 'sendgrid.com', 'sendgrid', 'https://docs.sendgrid.com'),
  ('Cloudflare', 'cloudflare.com', 'cloudflare', 'https://developers.cloudflare.com'),
  ('DigitalOcean', 'digitalocean.com', 'digitalocean', 'https://docs.digitalocean.com'),
  ('MongoDB', 'mongodb.com', 'mongodb', 'https://www.mongodb.com/docs'),
  ('Elastic', 'elastic.co', 'elastic', 'https://www.elastic.co/docs'),
  ('Grafana', 'grafana.com', 'grafana', 'https://grafana.com/docs'),
  ('PagerDuty', 'pagerduty.com', 'PagerDuty', 'https://developer.pagerduty.com'),
  ('Atlassian', 'atlassian.com', 'atlassian', 'https://developer.atlassian.com'),
  ('GitLab', 'gitlab.com', 'gitlabhq', 'https://docs.gitlab.com'),
  ('Bitbucket', 'bitbucket.org', 'atlassian', NULL),
  ('Asana', 'asana.com', 'Asana', 'https://developers.asana.com'),
  ('Monday', 'monday.com', 'mondaycom', 'https://developer.monday.com'),
  ('ClickUp', 'clickup.com', 'clickup', 'https://clickup.com/api'),
  ('Airtable', 'airtable.com', 'airtable', 'https://airtable.com/developers'),
  ('Zapier', 'zapier.com', 'zapier', 'https://platform.zapier.com'),
  ('Make', 'make.com', 'integromat', 'https://www.make.com/en/api-documentation'),
  ('Intercom', 'intercom.com', 'intercom', 'https://developers.intercom.com'),
  ('Zendesk', 'zendesk.com', 'zendesk', 'https://developer.zendesk.com'),
  ('Freshworks', 'freshworks.com', 'freshworks', 'https://developers.freshworks.com'),
  ('Salesforce', 'salesforce.com', 'salesforce', 'https://developer.salesforce.com'),
  ('Postman', 'postman.com', 'postmanlabs', 'https://learning.postman.com'),
  ('Docker', 'docker.com', 'docker', 'https://docs.docker.com'),
  ('HashiCorp', 'hashicorp.com', 'hashicorp', 'https://developer.hashicorp.com'),
  ('Terraform', 'terraform.io', 'hashicorp', NULL),
  ('Supabase', 'supabase.com', 'supabase', 'https://supabase.com/docs'),
  ('Firebase', 'firebase.google.com', 'firebase', 'https://firebase.google.com/docs'),
  ('Auth0', 'auth0.com', 'auth0', 'https://auth0.com/docs'),
  ('Okta', 'okta.com', 'okta', 'https://developer.okta.com'),
  ('Plaid', 'plaid.com', 'plaid', 'https://plaid.com/docs'),
  ('Square', 'squareup.com', 'square', 'https://developer.squareup.com'),
  ('PayPal', 'paypal.com', 'paypal', 'https://developer.paypal.com'),
  ('Braintree', 'braintreepayments.com', 'braintree', NULL),
  ('Algolia', 'algolia.com', 'algolia', 'https://www.algolia.com/doc'),
  ('Pinecone', 'pinecone.io', 'pinecone-io', 'https://docs.pinecone.io'),
  ('Weaviate', 'weaviate.io', 'weaviate', 'https://weaviate.io/developers'),
  ('Milvus', 'milvus.io', 'milvus-io', 'https://milvus.io/docs'),
  ('Cohere', 'cohere.com', 'cohere-ai', 'https://docs.cohere.com'),
  ('Mistral', 'mistral.ai', 'mistralai', 'https://docs.mistral.ai'),
  ('Perplexity', 'perplexity.ai', 'ppl-ai', 'https://docs.perplexity.ai'),
  ('Replicate', 'replicate.com', 'replicate', 'https://replicate.com/docs'),
  ('Hugging Face', 'huggingface.co', 'huggingface', 'https://huggingface.co/docs'),
  ('Stability AI', 'stability.ai', 'Stability-AI', 'https://platform.stability.ai/docs'),
  ('ElevenLabs', 'elevenlabs.io', 'elevenlabs', 'https://docs.elevenlabs.io'),
  ('Resend', 'resend.com', 'resend', 'https://resend.com/docs'),
  ('Neon', 'neon.tech', 'neondatabase', 'https://neon.tech/docs'),
  ('PlanetScale', 'planetscale.com', 'planetscale', 'https://planetscale.com/docs'),
  ('Turso', 'turso.tech', 'tursodatabase', 'https://docs.turso.tech'),
  ('Upstash', 'upstash.com', 'upstash', 'https://upstash.com/docs'),
  ('Convex', 'convex.dev', 'get-convex', 'https://docs.convex.dev'),
  ('Prisma', 'prisma.io', 'prisma', 'https://www.prisma.io/docs'),
  ('Drizzle', 'orm.drizzle.team', 'drizzle-team', 'https://orm.drizzle.team/docs'),
  ('Fly.io', 'fly.io', 'superfly', 'https://fly.io/docs'),
  ('Railway', 'railway.app', 'railwayapp', 'https://docs.railway.app'),
  ('Render', 'render.com', 'renderinc', 'https://render.com/docs'),
  ('Deno', 'deno.com', 'denoland', 'https://docs.deno.com'),
  ('Bun', 'bun.sh', 'oven-sh', 'https://bun.sh/docs'),
  ('Tailwind', 'tailwindcss.com', 'tailwindlabs', 'https://tailwindcss.com/docs'),
  ('Vercel AI SDK', 'sdk.vercel.ai', 'vercel', 'https://sdk.vercel.ai/docs'),
  ('LangChain', 'langchain.com', 'langchain-ai', 'https://docs.langchain.com'),
  ('LlamaIndex', 'llamaindex.ai', 'run-llama', 'https://docs.llamaindex.ai'),
  ('CrewAI', 'crewai.com', 'crewAIInc', 'https://docs.crewai.com'),
  ('Composio', 'composio.dev', 'ComposioHQ', 'https://docs.composio.dev'),
  ('n8n', 'n8n.io', 'n8n-io', 'https://docs.n8n.io'),
  ('Activepieces', 'activepieces.com', 'activepieces', 'https://www.activepieces.com/docs'),
  ('Midjourney', 'midjourney.com', 'midjourney', NULL),
  ('RunwayML', 'runwayml.com', 'runwayml', 'https://docs.runwayml.com'),
  ('Luma AI', 'lumalabs.ai', 'luma-ai', NULL),
  ('Cursor', 'cursor.com', 'getcursor', 'https://docs.cursor.com');
